
obj-y += smi.o port.o rtk_switch.o rtl8367c_asicdrv.o rtl8367c_asicdrv_phy.o rtl8367c_asicdrv_port.o rtl8367c_asicdrv_portIsolation.o rtl8367c_asicdrv_inbwctrl.o rtl8367c_asicdrv_rma.o rtl8367c_asicdrv_mirror.o rtl8367c_asicdrv_scheduling.o rtl8367c_asicdrv_lut.o
